# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproject.proto\x12\x07project\x1a\x1bgoogle/protobuf/empty.proto\"W\n\x07Project\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\x05\x12\x0e\n\x06status\x18\x05 \x01(\t\"H\n\x14\x43reateProjectRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\x05\"d\n\x14UpdateProjectRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\x05\x12\x0e\n\x06status\x18\x05 \x01(\t\"#\n\x15GetProjectByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x81\x01\n\x13ListProjectsRequest\x12:\n\x07\x66ilters\x18\x01 \x03(\x0b\x32).project.ListProjectsRequest.FiltersEntry\x1a.\n\x0c\x46iltersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"Y\n\x19\x42ulkCreateProjectResponse\x12\x18\n\x10projects_created\x18\x01 \x01(\x05\x12\"\n\x08projects\x18\x02 \x03(\x0b\x32\x10.project.Project2\xbe\x03\n\x0eProjectService\x12@\n\rCreateProject\x12\x1d.project.CreateProjectRequest\x1a\x10.project.Project\x12@\n\rUpdateProject\x12\x1d.project.UpdateProjectRequest\x1a\x10.project.Project\x12G\n\rDeleteProject\x12\x1e.project.GetProjectByIdRequest\x1a\x16.google.protobuf.Empty\x12\x42\n\x0eGetProjectById\x12\x1e.project.GetProjectByIdRequest\x1a\x10.project.Project\x12@\n\x0cListProjects\x12\x1c.project.ListProjectsRequest\x1a\x10.project.Project0\x01\x12Y\n\x12\x42ulkCreateProjects\x12\x1d.project.CreateProjectRequest\x1a\".project.BulkCreateProjectResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTPROJECTSREQUEST_FILTERSENTRY']._loaded_options = None
  _globals['_LISTPROJECTSREQUEST_FILTERSENTRY']._serialized_options = b'8\001'
  _globals['_PROJECT']._serialized_start=55
  _globals['_PROJECT']._serialized_end=142
  _globals['_CREATEPROJECTREQUEST']._serialized_start=144
  _globals['_CREATEPROJECTREQUEST']._serialized_end=216
  _globals['_UPDATEPROJECTREQUEST']._serialized_start=218
  _globals['_UPDATEPROJECTREQUEST']._serialized_end=318
  _globals['_GETPROJECTBYIDREQUEST']._serialized_start=320
  _globals['_GETPROJECTBYIDREQUEST']._serialized_end=355
  _globals['_LISTPROJECTSREQUEST']._serialized_start=358
  _globals['_LISTPROJECTSREQUEST']._serialized_end=487
  _globals['_LISTPROJECTSREQUEST_FILTERSENTRY']._serialized_start=441
  _globals['_LISTPROJECTSREQUEST_FILTERSENTRY']._serialized_end=487
  _globals['_BULKCREATEPROJECTRESPONSE']._serialized_start=489
  _globals['_BULKCREATEPROJECTRESPONSE']._serialized_end=578
  _globals['_PROJECTSERVICE']._serialized_start=581
  _globals['_PROJECTSERVICE']._serialized_end=1027
# @@protoc_insertion_point(module_scope)
